### ISSUE TITLE
FlashEnv的bug

### ISSUE THREAD

**Issue by taocp** [baidu/tera#397]
之前在deadlink上出现过，当时ssd有问题。

FlashEnv的`flash_paths_`变为空了（未预期的行为）。
没有复现过，待追查。

```
#0  0x0000003f0bf90339 in std::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string
    () from /usr/lib64/libstdc++.so.6
#1  0x000000000076fc1e in std::operator+<char, std::char_traits<char>, std::allocator<char> > (
    __lhs=@0x16de680, __rhs=@0x7fa660639610)
    at /usr/lib/gcc/x86_64-redhat-linux/3.4.5/../../../../include/c++/3.4.5/bits/basic_string.h:2005
#2  0x00000000009c8e80 in FlashRandomAccessFile (this=0x16fc260, posix_env=0x173c240, dfs_env=0x16fe2a0, 
    fname=@0x7fa660639610, fsize=18095809, vanish_allowed=false) at util/env_flash.cc:162
#3  0x00000000009c80a7 in leveldb::FlashEnv::NewRandomAccessFile (this=0x21e43420, fname=@0x7fa660639610, 
    fsize=18095809, result=0x7fa660639598) at util/env_flash.cc:337
#4  0x000000000099a4aa in leveldb::TableCache::FindTable (this=0x16f0540, dbname=@0x7fa660639770, 
    options=0x2207b248, file_number=9223373703302088842, file_size=18095809, handle=0x7fa6606396b8)
    at db/table_cache.cc:89
#5  0x000000000099a88d in leveldb::TableCache::NewIterator (this=0x16f0540, options=@0x258a2768, 
    dbname=@0x7fa660639770, file_number=9223373703302088842, file_size=18095809, smallest=@0x7fa660639780, 
    largest=@0x7fa660639790, tableptr=0x0) at db/table_cache.cc:143
#6  0x000000000099f714 in GetFileIterator (arg=0x16f0540, options=@0x258a2768, file_value=@0x7fa660639810)
    at db/version_set.cc:244
#7  0x00000000009b9a4a in leveldb::(anonymous namespace)::TwoLevelIterator::InitDataBlock (this=0x258a2730)
    at table/two_level_iterator.cc:169
#8  0x00000000009b969e in leveldb::(anonymous namespace)::TwoLevelIterator::Seek (this=0x258a2730, 
    target=@0x7fa6606398d0) at table/two_level_iterator.cc:97
#9  0x00000000009b4c5f in leveldb::(anonymous namespace)::IterWrapper::Seek (this=0x228ffac0, 
    k=@0x7fa6606398d0) at table/merger.cc:49
#10 0x00000000009b50de in leveldb::(anonymous namespace)::MergingIterator::Seek (this=0x2770eae0, 
    target=@0x7fa6606398d0) at table/merger.cc:149
#11 0x00000000009ec633 in leveldb::(anonymous namespace)::DBIter::Seek (this=0x2770d9d0, 
    target=@0x7fa660639980) at db/db_iter.cc:266
#12 0x0000000000833191 in tera::io::TabletIO::InitedScanInterator (this=0x21d09480, 
    start_tera_key=@0x7fa660639be0, scan_options=@0x7fa660639c20, scan_it=0x7fa660639ac8)
    at src/io/tablet_io.cc:595
#13 0x000000000083321d in tera::io::TabletIO::LowLevelScan (this=0x21d09480, start_tera_key=@0x7fa660639be0, 
```

```
(gdb) f 3
#3  0x00000000009c80a7 in leveldb::FlashEnv::NewRandomAccessFile (this=0x21e43420, fname=@0x7fa660639610, 
    fsize=18095809, result=0x7fa660639598) at util/env_flash.cc:337
337 util/env_flash.cc: No such file or directory.
    in util/env_flash.cc
(gdb) p flash_paths_
$5 = {<std::_Vector_base<std::basic_string<char, std::char_traits<char>, std::allocator<char> >,std::allocator<std::basic_string<char, std::char_traits<char>, std::allocator<char> > > >> = {
    _M_impl = {<std::allocator<std::basic_string<char, std::char_traits<char>, std::allocator<char> > >> = {<__gnu_cxx::new_allocator<std::basic_string<char, std::char_traits<char>, std::allocator<char> > >> = {<No data fields>}, <No data fields>}, _M_start = 0x16de680, _M_finish = 0x16de690, 
      _M_end_of_storage = 0x16de690}}, <No data fields>}
```

**Comment by 00k** [comment]
长期未复现，暂时关闭
