### ISSUE TITLE
写数据会出core，每秒写100个，数据量大约3G

### ISSUE THREAD

**Issue by MichelleZ** [baidu/tera#707]
```
#0  0x0000003f0b071890 in memcpy () from /lib64/tls/libc.so.6
#1  0x0000000000a12824 in leveldb::DecodeFixed32 (ptr=0x7f8c0f57c1dd <Address 0x7f8c0f57c1dd out of bounds>)
    at ./util/coding.h:66
#2  0x0000000000a6dd5f in leveldb::ReadBlock (file=0x22353540, options=@0x222d4a38, handle=@0x7f8c18cc6aa0, 
    result=0x7f8c18cc6a60) at table/format.cc:96
#3  0x0000000000a31501 in leveldb::Table::BlockReader (arg=0x2226ddd8, options=@0x222d4a38, index_value=@0x7f8c18cc6b30)
    at table/table.cc:285
#4  0x0000000000a333b7 in leveldb::(anonymous namespace)::TwoLevelIterator::InitDataBlock (this=0x222d4a00)
    at table/two_level_iterator.cc:169
#5  0x0000000000a331b8 in leveldb::(anonymous namespace)::TwoLevelIterator::SkipEmptyDataBlocksForward (this=0x222d4a00)
    at table/two_level_iterator.cc:137
#6  0x0000000000a330ea in leveldb::(anonymous namespace)::TwoLevelIterator::Next (this=0x222d4a00)
    at table/two_level_iterator.cc:119
#7  0x0000000000a322d0 in leveldb::TableIter::Next (this=0x22325c50) at table/table.cc:104
#8  0x0000000000a33707 in leveldb::IteratorWrapper::Next (this=0x22374730) at ./table/iterator_wrapper.h:46
#9  0x0000000000a330e1 in leveldb::(anonymous namespace)::TwoLevelIterator::Next (this=0x22374680)
    at table/two_level_iterator.cc:118
#10 0x0000000000a2e5d7 in leveldb::(anonymous namespace)::IterWrapper::Next (this=0x179dbe0) at table/merger.cc:47
#11 0x0000000000a2e38e in leveldb::(anonymous namespace)::MergingIterator::Next (this=0x17c7f80) at table/merger.cc:184
#12 0x0000000000a5ff31 in leveldb::DBImpl::DoCompactionWork (this=0x2235a900, compact=0x22362380) at db/db_impl.cc:1223
#13 0x0000000000a5e8da in leveldb::DBImpl::BackgroundCompaction (this=0x2235a900) at db/db_impl.cc:901
#14 0x0000000000a5e14f in leveldb::DBImpl::BackgroundCall (this=0x2235a900) at db/db_impl.cc:816
#15 0x0000000000a5e0b3 in leveldb::DBImpl::BGWork (db=0x2235a900) at db/db_impl.cc:808
#16 0x0000000000a513a6 in leveldb::ThreadPool::BGThread (this=0x17fa2d8) at util/thread_pool.cc:163
#17 0x0000000000a50c55 in leveldb::ThreadPool::BGThreadWrapper (arg=0x17fa2d8) at util/thread_pool.cc:46
#18 0x0000003f0b90610a in start_thread () from /lib64/tls/libpthread.so.0
#19 0x0000003f0b0c5ee3 in clone () from /lib64/tls/libc.so.6
#20 0x0000000000000000 in ?? ()
```

**Comment by stevenswong** [comment]
导致问题的原因是，ssd盘坏，打开文件出现Input/output error
